---

.script-git-submodule: &script-git-submodule
  - |
    git submodule sync --recursive
    git submodule update --init --recursive

.script-bootstrap-packer: &script-bootstrap-packer
  - |
    curl -skL -O https://github.com/hashicorp/packer/releases/download/nightly/packer_linux_amd64.zip
    sudo unzip -qq -o -d /usr/local/bin packer_linux_amd64.zip
    rm -rf packer_linux_amd64.zip

.script-bootstrap-vagrant: &script-bootstrap-vagrant
  - |
    curl -skL -O https://releases.hashicorp.com/vagrant/2.2.14/vagrant_2.2.14_x86_64.deb
    sudo dpkg -i vagrant_2.2.14_x86_64.deb
    rm -rf vagrant_2.2.14_*

.script-bootstrap-libvirt: &script-bootstrap-libvirt
  - |
    sudo apt-get update
    sudo apt-get install -y binutils bridge-utils dnsmasq-base ebtables gcc libguestfs-tools libvirt-clients libvirt-daemon-system libvirt-dev make qemu-kvm qemu-utils ruby-dev
    sudo vagrant plugin install vagrant-libvirt
    sudo systemctl start libvirtd

.script-bootstrap-ansible: &script-bootstrap-ansible
  - |
    sudo apt-get update
    sudo apt-get -y install ca-certificates curl gcc iproute2 pwgen python3 python3-dev sudo
    curl -skL https://bootstrap.pypa.io/get-pip.py | sudo -H python3 - --prefix=/usr/local
    sudo -H pip3 install --prefix=/usr/local --upgrade --requirement requirements.txt

.script-linters: &script-linters
  - |
    yamllint .
    ansible-lint
    flake8

.script-packer-build: &script-packer-build
  - |
    cd packer/$_PACKER_BUILDER_PROVIDER-$_PACKER_BUILDER_VERSION
    sudo packer build packer.json

.script-vagrant-cloud-provider-upload: &script-vagrant-cloud-provider-upload
  - |
    export _ORG=$CI_PROJECT_NAMESPACE
    export _BOX=$(echo $CI_PROJECT_NAME | sed "s/^vagrant-//g")-$_PACKER_BUILDER_VERSION
    export _PROVIDER=$_PACKER_BUILDER_PROVIDER
    if [[ -n "$CI_COMMIT_TAG" ]] && [[ "$CI_COMMIT_TAG" =~ ^$_PACKER_BUILDER_VERSION ]]; then
      export _VERSION=$(echo $CI_COMMIT_TAG | sed "s/^$_PACKER_BUILDER_VERSION+//g")
    else
      exit 0
    fi
    curl -skL \
      --header "Content-Type: application/json" \
      --header "Authorization: Bearer $VAGRANT_CLOUD_TOKEN" \
      --data "{ \"box\": { \"username\": \"$_ORG\", \"name\": \"$_BOX\", \"is_private\": false } }" \
      https://app.vagrantup.com/api/v1/boxes
    curl -skL \
      --header "Content-Type: application/json" \
      --header "Authorization: Bearer $VAGRANT_CLOUD_TOKEN" \
      --data "{ \"version\": { \"version\": \"$_VERSION\" } }" \
      https://app.vagrantup.com/api/v1/box/$_ORG/$_BOX/versions
    curl -skL \
      --request DELETE \
      --header "Content-Type: application/json" \
      --header "Authorization: Bearer $VAGRANT_CLOUD_TOKEN" \
      https://app.vagrantup.com/api/v1/box/$_ORG/$_BOX/version/$_VERSION/provider/$_PROVIDER
    curl -skL \
      --header "Content-Type: application/json" \
      --header "Authorization: Bearer $VAGRANT_CLOUD_TOKEN" \
      --data "{ \"provider\": { \"name\": \"$_PROVIDER\" } }" \
      https://app.vagrantup.com/api/v1/box/$_ORG/$_BOX/version/$_VERSION/providers
    _UPLOAD_PATH=$(curl -skL \
      --header "Authorization: Bearer $VAGRANT_CLOUD_TOKEN" \
      https://app.vagrantup.com/api/v1/box/$_ORG/$_BOX/version/$_VERSION/provider/$_PROVIDER/upload | jq -r .upload_path)
    curl -skL \
      --request PUT \
      --header "Connection: keep-alive" \
      --upload-file output-vagrant/package.box \
      $_UPLOAD_PATH
    curl -skL \
      --request PUT \
      --header "Authorization: Bearer $VAGRANT_CLOUD_TOKEN" \
      https://app.vagrantup.com/api/v1/box/$_ORG/$_BOX/version/$_VERSION/release

.job-packer: &job-packer
  script:
    - *script-bootstrap-packer
    - *script-bootstrap-vagrant
    - *script-bootstrap-libvirt
    - *script-bootstrap-ansible
    - *script-linters
    - *script-packer-build
    - *script-vagrant-cloud-provider-upload

default:
  before_script:
    - *script-git-submodule

libvirt-13.6.0:
  <<: *job-packer
  variables:
    _PACKER_BUILDER_PROVIDER: "libvirt"
    _PACKER_BUILDER_VERSION: "13.6.0"

libvirt-13.5.0:
  <<: *job-packer
  variables:
    _PACKER_BUILDER_PROVIDER: "libvirt"
    _PACKER_BUILDER_VERSION: "13.5.0"
