---

.script-git-submodule: &script-git-submodule
  - |
    git submodule sync --recursive
    git submodule update --init --recursive

.script-bootstrap-packer: &script-bootstrap-packer
  - |
    curl -skL -O https://github.com/hashicorp/packer/releases/download/nightly/packer_linux_amd64.zip
    sudo unzip -qq -o -d /usr/local/bin packer_linux_amd64.zip
    rm -rf packer_linux_amd64.zip

.script-bootstrap-vagrant: &script-bootstrap-vagrant
  - |
    curl -skL -O https://releases.hashicorp.com/vagrant/2.2.14/vagrant_2.2.14_x86_64.deb
    sudo dpkg -i vagrant_2.2.14_x86_64.deb
    rm -rf vagrant_2.2.14_*

.script-bootstrap-libvirt: &script-bootstrap-libvirt
  - |
    sudo apt-get update
    sudo apt-get install -y binutils bridge-utils dnsmasq-base ebtables gcc libguestfs-tools libvirt-clients libvirt-daemon-system libvirt-dev make qemu-kvm qemu-utils ruby-dev
    sudo vagrant plugin install vagrant-libvirt
    sudo systemctl start libvirtd

.script-bootstrap-ansible: &script-bootstrap-ansible
  - |
    sudo apt-get update
    sudo apt-get -y install ca-certificates curl gcc iproute2 pwgen python3 python3-dev sudo
    curl -skL https://bootstrap.pypa.io/get-pip.py | sudo -H python3 - --prefix=/usr/local
    sudo -H pip3 install --prefix=/usr/local --upgrade --requirement requirements.txt

.script-linters: &script-linters
  - |
    yamllint .
    ansible-lint
    flake8

.script-packer-build: &script-packer-build
  - |
    cd packer/$_PACKER_BUILDER_PROVIDER-$_PACKER_BUILDER_VERSION
    sudo packer build packer.json

.script-vagrant-cloud: &script-vagrant-cloud
  - |
    vagrant cloud auth login --token $VAGRANT_TOKEN
    export _VAGRANT_BOX=$CI_PROJECT_NAMESPACE/$(echo $CI_PROJECT_NAME | sed 's/^vagrant-//g')
    if [[ -n "$CI_COMMIT_TAG" ]] && [[ "$CI_COMMIT_TAG" =~ ^$PACKER_BUILDER_VERSION ]]; then
      vagrant cloud provider delete --force $_VAGRANT_BOX $_PACKER_BUILDER_PROVIDER $CI_COMMIT_TAG || echo $?
      vagrant cloud provider create $_VAGRANT_BOX $_PACKER_BUILDER_PROVIDER $CI_COMMIT_TAG
      vagrant cloud provider upload --direct $_VAGRANT_BOX $_PACKER_BUILDER_PROVIDER $CI_COMMIT_TAG output-vagrant/package.box
    elif [[ -n "$CI_COMMIT_BRANCH" ]] && [[ "$CI_COMMIT_BRANCH" =~ master ]]; then
      vagrant cloud provider delete --force $_VAGRANT_BOX $_PACKER_BUILDER_PROVIDER $_PACKER_BUILDER_VERSION || echo $?
      vagrant cloud provider create $_VAGRANT_BOX $_PACKER_BUILDER_PROVIDER $_PACKER_BUILDER_VERSION
      vagrant cloud provider upload --direct $_VAGRANT_BOX $_PACKER_BUILDER_PROVIDER $_PACKER_BUILDER_VERSION output-vagrant/package.box
    fi

.job-packer: &job-packer
  script:
    - *script-bootstrap-packer
    - *script-bootstrap-vagrant
    - *script-bootstrap-libvirt
    - *script-bootstrap-ansible
    - *script-linters
    - *script-packer-build
    - *script-vagrant-cloud

default:
  before_script:
    - *script-git-submodule

libvirt-13.6:
  <<: *job-packer
  variables:
    _PACKER_BUILDER_PROVIDER: "libvirt"
    _PACKER_BUILDER_VERSION: "13.6"

libvirt-13.5:
  <<: *job-packer
  variables:
    _PACKER_BUILDER_PROVIDER: "libvirt"
    _PACKER_BUILDER_VERSION: "13.5"
