---

# (c) Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- hosts: all
  remote_user: root
  become: true
  tasks:
    - name: include default variables
      include_vars: "./vars/main.yml"

    - name: include release specific variables
      include_vars: "{{ lookup('first_found', _params) }}"
      vars:
        _params:
          files:
            - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
            - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
            - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
            - "{{ ansible_distribution | lower }}.yml"
            - "{{ ansible_os_family | lower }}.yml"
          paths:
            - "./vars"
      ignore_errors: true

    - name: include release specific tasks
      include_tasks: "{{ lookup('first_found', _params) }}"
      vars:
        _params:
          files:
            - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
            - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
            - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
            - "{{ ansible_distribution | lower }}.yml"
            - "{{ ansible_os_family | lower }}.yml"
          paths:
            - "./tasks"
      ignore_errors: true

    - name: include default tasks
      include_tasks: "./tasks/main.yml"

    - name: include role
      include_role:
        name: python

    - name: include role
      include_role:
        name: locales

    - name: include role
      include_role:
        name: timezone

    - name: include role
      include_role:
        name: sshd

    - name: include role
      include_role:
        name: bootstrap

    - name: include role
      include_role:
        name: kernel

    - name: include role
      include_role:
        name: git

    - name: include role
      include_role:
        name: ansible

    - name: include role
      include_role:
        name: packer

    - name: include role
      include_role:
        name: vagrant

    - name: include role
      include_role:
        name: docker

    - name: useradd
      user:
        name: "{{ item.name }}"
        groups: "{{ item.groups }}"
        append: true
        state: "present"
      loop:
        - { name: "vagrant", groups: "docker" }

    - name: include role
      include_role:
        name: libvirt

    - name: useradd
      user:
        name: "{{ item.name }}"
        groups: "{{ item.groups }}"
        append: true
        state: "present"
      loop:
        - { name: "vagrant", groups: "kvm" }
        - { name: "vagrant", groups: "libvirt" }

    - name: sudo -u vagrant vagrant plugin install vagrant-libvirt
      environment:
        PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      shell: |
        set -euo pipefail
        ln -fs /usr/bin/ld.gold /usr/bin/ld
        TMP_DIR="$(mktemp -d)" \
          && cd $TMP_DIR \
          && curl -skL -m 300 -O https://github.com/alvistack/vagrant-libvirt-vagrant-libvirt/releases/download/0.4.1/vagrant-libvirt-0.4.1+virtiofs.gem \
          && sudo -u vagrant vagrant plugin install $TMP_DIR/vagrant-libvirt-0.4.1+virtiofs.gem \
          && rm -rf $TMP_DIR
      args:
        executable: "/bin/bash"
      register: result
      until: result is succeeded
      changed_when: result is not succeeded

    - name: include role
      include_role:
        name: virtualbox

    - name: useradd
      user:
        name: "{{ item.name }}"
        groups: "{{ item.groups }}"
        append: true
        state: "present"
      loop:
        - { name: "vagrant", groups: "vboxusers" }

    - name: include role
      include_role:
        name: molecule

    - name: include role
      include_role:
        name: gitlab_runner
